version: "3.7"

services:
  rabbitmq:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  celery-flower:
    image: mher/flower
    command: ["flower", "--broker=amqp://user:bitnami@rabbitmq:5672", "--port=5555"]
    # environment:
    #   - AMQP_USERNAME=user
    #   - AMQP_PASSWORD=bitnami
    #   - AMQP_ADMIN_USERNAME=user
    #   - AMQP_ADMIN_PASSWORD=bitnami
    #   - AMQP_HOST=rabbitmq
    #   - AMQP_PORT=5672
    #   - AMQP_ADMIN_HOST=rabbitmq
    #   - AMQP_ADMIN_PORT=15672
    #   - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis

  fastapi:
    image: "forrestzhang/fastapi-celery-worker"
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - "./:/app"
    command: "poetry run hypercorn app/app/main:app --bind 0.0.0.0:8000 --reload"

  worker:
    image: "forrestzhang/fastapi-celery-worker"
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - "./:/app"
      - "/Users/forrest/Data/Ref:/Data"
    command: "poetry run celery worker -A app.app.worker.celery_worker -l info -Q test-queue -c 1"

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
